services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data_volume:/qdrant_data
    networks:
      - PyPlexitas

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  qdrant_data_volume:
    driver: local

networks:
  PyPlexitas:
    driver: bridge